### ISSUE TITLE
GitHub Actions CI could be optimized

### ISSUE THREAD

**Issue by tzq0301** [dominikbraun/graph#139]
1. Currently, CI will be triggered only when PR. However, some issues/errors, which might be reported by CI, should be resolved before PR.
2. Upgrade the version of actions/setup-go to v4 & actions/checkout to v3.
3. Support Matrix Testing.

I'm willing to do this optimization. The result could be seen in the 'Actions' bar of my reposiroty ([tzq0301/graph](https://github.com/tzq0301/graph/actions)) like [this](https://github.com/tzq0301/graph/actions/runs/5287556205).

**Comment by dominikbraun** [comment]
Good idea, thanks.
