### ISSUE TITLE
multigraph support

### ISSUE THREAD

**Issue by miparnisari** [dominikbraun/graph#168]
I couldn't find documentation for this. How do I build a directed graph that allows more than one edge between the same two nodes? https://en.wikipedia.org/wiki/Multigraph

**Comment by miparnisari** [comment]
> We actually had a note about this in the README, I wonder where that went...

it disappeared because it's now supported? 😄 🤣 

> May I ask about your use-case? 

The graphs that i want to build are multigraphs. I only need a `HasCycle` algorithm on it.

> Could there be a workaround?

Another library :( https://pkg.go.dev/gonum.org/v1/gonum/graph/multi

**Comment by dominikbraun** [comment]
> it disappeared because it's now supported? 😄 🤣

I would love to be able to confirm this, but I'm afraid I can't 😅 

> Another library :( https://pkg.go.dev/gonum.org/v1/gonum/graph/multi

This is actually a good example for why multigraphs haven't been implemented in this library yet: gonum's `multi` package is basically a second library. So I would love to support multigraphs here as well, but it means that you have to implement most things twice.

**Comment by miparnisari** [comment]
I ended up using `gonum`
