### ISSUE TITLE
Add `Order` and `Size` methods

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/graph#21]
The `Graph` interface should have an `Order` method returning the number of vertices and a `Size` method returning the number of edges in the graph.

**Comment by Nightfurex** [comment]
Hey can I work on this

**Comment by dominikbraun** [comment]
@pangeran-bottor This has been released in [v0.11.0](https://github.com/dominikbraun/graph/releases/tag/v0.11.0).
