### ISSUE TITLE
Make edge layout and memory consumption configurable

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/graph#24]
Currently, an edge is represented as an `Edge[T any]`, where the source and target vertices are of type `T`. This is convenient when retrieving an edge, because the user can operate on the source and target value directly - but the downside is that if  `T` is a larger custom type, the memory consumption is equally large. In fact, each instance of `T` is stored multiple times: In `vertices`, `edges`, `outEdges`, and `inEdges`.

The other option is to only store the hash values of the vertices instead of the vertices themselves. This means that the user has to look up the actual vertices by their hash values first, but the memory consumption will be lower in cases where there are large custom data types.

All in all, this is a trade-off between memory efficiency and developer-friendliness. Whether one or the other is preferable depends on the use case, and therefore, this behavior should be configurable.

---

My proposal is to introduce a new functional option that can be passed to `New` when creating a graph. It should make `Edge[T any]` store hash values instead of vertices (which is possible because `T` is `any` and hash values are of type `K comparable`). This function could be called `WithHashValues`:

```go
g := graph.New(myHashingFunction, graph.Directed(), graph.WithHashValues())
```

Another name could be `WithHashEdges` or something like that.

**Comment by geoah** [comment]
This is an interesting approach but I’m not sure how it would look in real life.

The method signatures would still return K/T specifically unless you want to make Edge() for example accept `interface{}` which would be kinda missing the point. 

I might be missing something here.

ps. What happens to the methods that will come out of 25 that will have to use the graph in this case? 
—-

Alternative would be  having a different constructor? `NewByValues(…) GraphByValues` that has a different interface and basically is a wrapper for `Graph` (and also extends it)?

**Comment by dominikbraun** [comment]
So I played around quite a bit and tried to solve this by using two versions of `inEdges` and `outEdges` for storing the edges, one that stores `Edge[T]` and one that stores `Edge[K]` - and I really don't like it so far. Especially with the new `Store` interface in place, this will get confusing.

This would be the only way that would be ok for me, but of course, this doesn't work because of the type parameters: https://go.dev/play/p/Zi0H2EUNHa6

I agree that a wrapper type would be the cleanest way to solve this, if any. But I'd like to wait at least for #12 and #25, so I'm going to close this issue and create a new one once we exactly know what we're needing.
