### ISSUE TITLE
Update documentation to explicitly ignore errors returned by `AddVertex`

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/graph#54]
At the moment, `AddVertex` calls in the documentation (README + GoDoc) look like this:

```go
g.AddVertex(1, 2)
```

But `AddVertex` returns an error, and that should be made clear in the docs. The error should be ignored explicitly, just as with the `AddEdge` calls:

```go
_ = g.AddVertex(1, 2)
```

Again, this should be done in both the README and the code comments.

**Comment by vinicio** [comment]
Hi! Can I take this one?

**Comment by dominikbraun** [comment]
Sure 🙂
