### ISSUE TITLE
(In-)Neighbors Directed Graph

### ISSUE THREAD

**Issue by alexloebel** [dominikbraun/graph#55]
Hi, 

I am trying to find the in-neighbors for a node in a directed graph. To do so, I thought about using the `AdjacencyMap` since the documentation says: 

> AdjacencyMap computes and returns an adjacency map containing all vertices in the graph.
> There is **an entry for each vertex**, and each of those entries is **another map whose keys are
> the hash values of the adjacent vertices**.

However, it turns out, that in this example (omitting error checks for shortness): 
```
g.AddVertex(0)
g.AddVertex(1)
g.AddVertex(2)

g.AddEdge(0, 1)
g.AddEdge(0, 2)

m, err := g.AdjacencyMap()
log.Println("Testing key 0: ", m[0])
log.Println("Testing key 1: ", m[1])
log.Println("Testing key 2: ", m[2])
```
we get: 
```
Testing key 0:  map[1:{0 1 {map[] 0}} 2:{0 2 {map[] 0}}]
Testing key 1:  map[]
Testing key 2:  map[]
``` 
Empty maps for node 1 and node 2 while they do have node 0 as in-neighbor. 
This is not necessarily wrong if one says that vertices are only adjacent if there is an edge from the source vertex to this vertex. However, for directed graphs this is not well-defined without further information. 

Hence, I'd say at least this should be described better in the documentation. Even more, I want to propose something along a `neighbors(vertex)` function which could then also be configured with in- and out-neighbors in the case of directed graphs.

Let me know how you think about this proposal and if there are meaningful starting points for this.

**Comment by dominikbraun** [comment]
This behavior is indeed intended. In a directed graph, if there is an edge `(a, b)`, `b` is an adjacency of `a` but `a` isn't an adjacency of `b`. This is not a strict definition in graph theory, but a [common one](https://en.wikipedia.org/wiki/Adjacency_matrix#Directed_graphs).

I think you're looking for [PredecessorMap](https://github.com/dominikbraun/graph/blob/v0.13.0/graph.go#L71), which creates a map of the in-neighbors for each node. In a directed graph, it is the "opposite" of `AdjacencyMap`.

Is this helpful for you? Thanks for pointing this out anyway, I'll try to make the documentation more clear here.

**Comment by alexloebel** [comment]
You're right - the PredecessorMap is exactly what I need - thank you!
