### ISSUE TITLE
Has graph supported finding all paths between Vertex A and Vertex B ？

### ISSUE THREAD

**Issue by evanscat** [dominikbraun/graph#59]

**Comment by dominikbraun** [comment]
No, at the time being, `graph` only supports finding the _shortest_ path between two vertices. Finding all paths efficiently is one of the hardest problems in graph theory.

If you can specialize your use case with a framework of assumptions that are safe to make, you can implement your own path search using [BFS](https://pkg.go.dev/github.com/dominikbraun/graph#BFS) or [DFS](https://pkg.go.dev/github.com/dominikbraun/graph#DFS) - but providing a built-in function in the library that works for all use cases in all graphs is close to impossible. It might be easier in directed graphs, maybe I'll come up with an algorithm for this in the future.

**Comment by evanscat** [comment]
We use graph in power grid topological analysising. The graph among power grid are always DAG and the most common use case is to find all power supply path.
I'll use BFS or DFS to implement my own algorithm.Thanks a lot!

**Comment by dominikbraun** [comment]
Thanks! If you want to further share your use cases or need guidance, just reach out.
