### ISSUE TITLE
DOT not found

### ISSUE THREAD

**Issue by HCY-ASLEEP** [dominikbraun/graph#63]
![image](https://user-images.githubusercontent.com/76894615/202907547-c18dc01f-ba4c-4e2f-ab8a-18e4357dc53b.png)

![image](https://user-images.githubusercontent.com/76894615/202907305-e92dbf66-257d-48ad-ab1d-b6b6f85d9e1e.png)
Can anyone tell me how to fix this problem?

**Comment by dominikbraun** [comment]
You're importing the `image/draw` package. You need to import `github.com/dominikbraun/graph/draw` instead.

**Comment by HCY-ASLEEP** [comment]
> github.com/dominikbraun/graph/draw

Thank you very much! It works well!
