### ISSUE TITLE
How to draw a graph as beautiful as in README?

### ISSUE THREAD

**Issue by SilverRainZ** [dominikbraun/graph#81]
Hi, I am trying to find a package that can draw beautiful directed graphs. It seems the DOT files generated by draw package does not contains any predeinfed attributes. Does the images in README is drawed by DOT? What vertex/edge attributes is it using?

Thank you~

Example code:

```go
g := graph.New(graph.IntHash)

_ = g.AddVertex(1)
_ = g.AddVertex(2)
_ = g.AddVertex(3)
_ = g.AddVertex(4)
_ = g.AddVertex(5)

_ = g.AddEdge(1, 2)
_ = g.AddEdge(1, 4)
_ = g.AddEdge(2, 3)
_ = g.AddEdge(2, 4)
_ = g.AddEdge(2, 5)
_ = g.AddEdge(3, 5)
```

Corrsponding image in REDAME:

![README](https://raw.githubusercontent.com/dominikbraun/graph/main/img/simple.svg)

The image I got:

![output](https://user-images.githubusercontent.com/8090459/221390004-975a16a7-37a7-455e-b2ff-8bbc08df28f9.svg)

**Comment by dominikbraun** [comment]
Hi! You need the attributes [`colorscheme`](https://graphviz.org/docs/attrs/colorscheme/), [`color`](https://graphviz.org/docs/attrs/color/), [`fillcolor`](https://graphviz.org/docs/attrs/fillcolor/), and if you want, [`fontname`](https://graphviz.org/docs/attrs/fontname/). Additionally, you need the [`style`](https://graphviz.org/docs/attrs/style/) attribute set to `filled`.

You can add these attributes using the `VertexAttribute` option. A graph like in the example could be created as follows (using the [Brewer color scheme](https://graphviz.org/doc/info/colors.html#brewer)):

```go
_ = g.AddVertex(1, graph.VertexAttribute("colorscheme", "blues3"), graph.VertexAttribute("style", "filled"), graph.VertexAttribute("color", "2"), graph.VertexAttribute("fillcolor", "1"));
_ = g.AddVertex(2, graph.VertexAttribute("colorscheme", "greens3"), graph.VertexAttribute("style", "filled"), graph.VertexAttribute("color", "2"), graph.VertexAttribute("fillcolor", "1"));
_ = g.AddVertex(3, graph.VertexAttribute("colorscheme", "purples3"), graph.VertexAttribute("style", "filled"), graph.VertexAttribute("color", "2"), graph.VertexAttribute("fillcolor", "1"));
_ = g.AddVertex(4, graph.VertexAttribute("colorscheme", "ylorbr3"), graph.VertexAttribute("style", "filled"), graph.VertexAttribute("color", "2"), graph.VertexAttribute("fillcolor", "1"));
_ = g.AddVertex(5, graph.VertexAttribute("colorscheme", "reds3"), graph.VertexAttribute("style", "filled"), graph.VertexAttribute("color", "2"), graph.VertexAttribute("fillcolor", "1"));
```

Rendering this will yield the following graph:

<img width="771" alt="Screenshot 2023-02-26 at 12 11 07 PM" src="https://user-images.githubusercontent.com/36575275/221406984-924fe9fa-4bf1-4194-8df9-ce8207464568.png">

To arrange the nodes like in the example, you can use the [osage](https://graphviz.org/docs/layouts/osage/) engine for rendering the DOT file - I think this can be done by passing the `-Kosage` flag to the `dot` command. The DOT playground yields the following graph:

<img width="878" alt="Screenshot 2023-02-26 at 12 14 47 PM" src="https://user-images.githubusercontent.com/36575275/221407122-84eeaf80-f9e1-413b-8341-b97a9d8d5f78.png">

Now, all you need to do is to add the `width` and `height` vertex attributes, and set the `fixedheight` attribute to `true`.

**Comment by SilverRainZ** [comment]
@dominikbraun Thanks for your detailed answer, it is helpful to me. :D
