### ISSUE TITLE
Graph attributes

### ISSUE THREAD

**Issue by RealHarshThakur** [dominikbraun/graph#91]
Is it possible to have a generic Graph attributes that can be passed like Vertex/Edge to GraphViz?

I was looking at adding this but couldn't find anything :
`	rankdir=LR;
`

**Comment by dominikbraun** [comment]
Hi, graph attributes for `draw.DOT` will likely come with the next release. General graph attributes are planned too, but require a bit more thought to implement.

**Comment by dominikbraun** [comment]
Support for global graph attributes for `draw.DOT` has been added in [release v0.17.0](https://github.com/dominikbraun/graph/releases/tag/v0.17.0):

```go
_ = draw.DOT(g, file, draw.GraphAttribute("label", "my-graph"))
```

CC @RealHarshThakur @christophetd

**Comment by christophetd** [comment]
Thanks for the note! I had to temporarily switch to https://github.com/awalterschulze/gographviz for this, I guess I can switch back to `graph` now

**Comment by RealHarshThakur** [comment]
Amazing, thanks for the quick turnaround! :)

**Comment by dominikbraun** [comment]
Since this issue only concerns Graphviz, I'm going to close it for now. There's also #76 for general graph attributes.
