### ISSUE TITLE
please support remove vertex

### ISSUE THREAD

**Issue by liuxiaomeiG** [dominikbraun/graph#97]

**Comment by davis-haba** [comment]
+1

**Comment by dominikbraun** [comment]
Absolutely. I‘ll try to add it in the upcoming release.

**Comment by dominikbraun** [comment]
@liuxiaomeiG @davis-haba `RemoveVertex` has been released in [graph v0.18.0](https://github.com/dominikbraun/graph/releases/tag/v0.18.0).

**Comment by davis-haba** [comment]
Thank you!

**Comment by liuxiaomeiG** [comment]
Thank you
